version: 2
image: ubuntu:16.04
jobs:
  install-dependencies:
    docker:
      - image: node:12-slim
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: node:12-slim
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: |
            npm run tsc

      - run:
          name: push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/adotei-back:latest .
            docker push $DOCKER_USER/adotei-back:latest

workflows:
  version: 2
  lint-test-and-build:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: /^(dev|master)$/

      - build:
          requires:
            - build
          filters:
            branches:
              only: /^(dev|master)$/
    # - deploy:
    #     requires:
    #       - build
    #     filters:
    #       tags:
    #         only: /^([0-9]+).([0-9]+).([0-9]+)$/
    #       branches:
    #         ignore: /.*/
