version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      # - run:
      #     name: update-npm
      #     command: 'sudo npm install -g npm@5'
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
      #     name: install dependency
      #     command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      # - run:
      #     name: test
      #     command: npm run test

      - setup_remote_docker:
          version: 19.03.13
          ##docker_layer_caching: true
      - run:
          name: login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: push
          command: docker build -t company/app:$CIRCLE_BRANCH .

      - run:
          name: push
          command: docker push company/app:$CIRCLE_BRANCH
