version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: |
            npm i
            npm run tsc

      - run:
          name: push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/adotei-back:latest .
            docker push $DOCKER_USER/adotei-back:latest

  deploy:
    docker:
      - image: circleci/node:lts
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      HEROKU_APP: $HEROKU_APP
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh # run a script to set up Heroku

      - run:
          command: |
            git push heroku sequential-branch-filter:master
            heroku run rake db:migrate
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  lint-test-and-build:
    jobs:
      - build:
          filters:
            branches:
              only: /^(dev|master)$/
    # - deploy:
    #     requires:
    #       - build
    #     filters:
    #       tags:
    #         only: /^([0-9]+).([0-9]+).([0-9]+)$/
    #       branches:
    #         ignore: /.*/
