version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.3
      steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@5'
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install dependency
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
      #   - run:
      #       name: test
      #       command: npm run test

      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: docker build
          command: docker build -t $DOCKER_USER/adotei-back:latest .

      - run:
          name: docker push
          command: docker push $DOCKER_USER/adotei-back:latest

      - run:
          name: Heroku install
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: heroku login
          command: heroku auth:token HEROKU_API_KEY

      - run:
          name: heroku container registry login
          command: heroku container:login

      - run:
          name: heroku container:push web
          command: heroku container:push web -a adotei-back

      - run:
          name: Subir o container para o server
          command: heroku container:release web -a adotei-back
