version: 2.1

jobs:
  context: adotei
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:$TAG
