version: 2.1

jobs:
  context: adotei
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      # build and push Docker image
      - run: |
          docker build -t icarodgl/$CIRCLE_PR_REPONAME:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push icarodgl/$CIRCLE_PR_REPONAME:$TAG
